WIP

diff --git a/dotfiles/.git_commands/git-update-branch b/dotfiles/.git_commands/git-update-branch
--- a/dotfiles/.git_commands/git-update-branch
+++ b/dotfiles/.git_commands/git-update-branch
@@ -20,12 +20,9 @@ given it's implied to be the default branch of the implied remote.
 
 SUBDIRECTORY_OK="yes" . "$(git --exec-path)/git-sh-setup"
 
-while test $# != 0; do
+while [ "$#" != 0 ]; do
     case "$1" in
-    --)
-        shift
-        break
-        ;;
+    --) shift; break;;
     esac
     shift
 done
@@ -41,11 +38,11 @@ if [ -z "$1" ]; then
     branch="$(git remote show $remote | grep 'HEAD branch' | cut -d' ' -f5)"
 fi
 
-git branch -r | grep -qn ${branch} || die "Branch '$branch' does not exist"
+git branch -r | grep -qn "$branch" || die "Branch '$branch' does not exist"
 curbranch=$(git rev-parse --abbrev-ref HEAD)
 [ "$branch" != "$curbranch" ] || die "Cannot update $branch"
 
-git fetch "$remote" "$branch:$branch"
+git fetch "$remote" "$branch:$branch" || die "Failed to fetch branch '$branch' from '$remote'"
 git rebase "$branch"
 
 if [ -f "$(git rev-parse --git-dir)/REBASE_HEAD" ]; then
